export interface Certificate {
  id: string;
  title: string;
  issuer: string;
  date: string;
  category: "Data Science" | "Full Stack" | "Android" | "Security" | "Cloud";
  image: string;
  skills: string[];
  credentialUrl: string;
  description: string;
}

export const certificates: Certificate[] = [
  {
    id: "ds-dl-1",
    title: "Neural Networks and Deep Learning",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050508_798.jpg",
    skills: ["Neural Networks", "Deep Learning", "Python", "Backpropagation"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Foundational course on building and training deep neural networks.",
  },
  {
    id: "ds-dl-2",
    title: "Improving Deep Neural Networks",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_533.jpg",
    skills: ["Hyperparameter Tuning", "Regularization", "Optimization"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Advanced techniques for making neural networks perform better.",
  },
  {
    id: "ds-dl-3",
    title: "Structuring Machine Learning Projects",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_575.jpg",
    skills: ["ML Strategy", "Error Analysis", "Target Setting"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Learning how to build a successful machine learning project.",
  },
  {
    id: "ds-dl-4",
    title: "Convolutional Neural Networks",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_673.jpg",
    skills: ["CNNs", "Computer Vision", "Object Detection"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Deep dive into computer vision using convolutional neural networks.",
  },
  {
    id: "ds-dl-5",
    title: "Sequence Models",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050532_741.png",
    skills: ["RNNs", "LSTM", "NLP", "Sequence Modeling"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Building models for natural language processing and other sequence data.",
  },
  {
    id: "fs-1",
    title: "Full Stack Web Development",
    issuer: "Evangadi",
    date: "2022",
    category: "Full Stack",
    image: "/certificates/IMG_20260617_050508_926.jpg",
    skills: ["React", "Node.js", "MySQL", "Express"],
    credentialUrl: "#",
    description: "Comprehensive bootcamp covering modern web technologies.",
  },
  {
    id: "ds-ml-spec",
    title: "Machine Learning Specialization",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050509_061.jpg",
    skills: ["Machine Learning", "Supervised Learning", "Unsupervised Learning"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Mastering fundamental AI concepts and tools.",
  },
  {
    id: "ds-ai-everyone",
    title: "AI For Everyone",
    issuer: "DeepLearning.AI",
    date: "2022",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050509_088.jpg",
    skills: ["AI Strategy", "AI Ethics", "Workflow"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "A non-technical introduction to AI concepts and their impact.",
  },
  {
    id: "ds-ml-1",
    title: "Supervised Machine Learning",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_028.jpg",
    skills: ["Regression", "Classification", "Logistic Regression"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Learning how to build supervised machine learning models.",
  },
  {
    id: "ds-ml-2",
    title: "Advanced Learning Algorithms",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_043.jpg",
    skills: ["Decision Trees", "Random Forests", "Neural Networks"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Exploring sophisticated algorithms for predictive modeling.",
  },
  {
    id: "ds-ml-3",
    title: "Unsupervised Learning & Recommenders",
    issuer: "DeepLearning.AI",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_086.jpg",
    skills: ["Clustering", "Anomaly Detection", "Recommender Systems"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Learning unsupervised learning techniques and building recommendation engines.",
  },
  {
    id: "ds-math-spec",
    title: "Mathematics for Machine Learning",
    issuer: "Imperial College London",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_090.jpg",
    skills: ["Linear Algebra", "Calculus", "PCA"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "The mathematical foundations required for machine learning.",
  },
  {
    id: "ds-math-1",
    title: "Linear Algebra for ML",
    issuer: "Imperial College London",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_168.jpg",
    skills: ["Vectors", "Matrices", "Eigenvalues"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Core linear algebra concepts for data representation.",
  },
  {
    id: "ds-math-2",
    title: "Multivariate Calculus for ML",
    issuer: "Imperial College London",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_480.jpg",
    skills: ["Gradients", "Optimization", "Chain Rule"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Calculating gradients for training machine learning models.",
  },
  {
    id: "ds-math-3",
    title: "PCA for ML",
    issuer: "Imperial College London",
    date: "2023",
    category: "Data Science",
    image: "/certificates/IMG_20260617_050514_518.jpg",
    skills: ["Dimensionality Reduction", "Eigen-decomposition"],
    credentialUrl: "https://www.coursera.org/account/accomplishments/verify/9L5J8Q8J8J8J",
    description: "Using Principal Component Analysis to compress data.",
  },
];
